
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author saqib khan
 */
public class Home extends javax.swing.JFrame {

    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        bookTickets = new javax.swing.JMenuItem();
        canceltickets = new javax.swing.JMenuItem();
        showAllTickets = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addFlights = new javax.swing.JMenuItem();
        searchFlights = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        back = new javax.swing.JMenuItem();
        exits = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Ticket");

        bookTickets.setText("Book Ticket");
        bookTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketsActionPerformed(evt);
            }
        });
        jMenu1.add(bookTickets);

        canceltickets.setText("Cancel Ticket");
        canceltickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelticketsActionPerformed(evt);
            }
        });
        jMenu1.add(canceltickets);

        showAllTickets.setText("All Booked Tickets");
        showAllTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllTicketsActionPerformed(evt);
            }
        });
        jMenu1.add(showAllTickets);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Flight");

        addFlights.setText("Add Flight");
        addFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightsActionPerformed(evt);
            }
        });
        jMenu2.add(addFlights);

        searchFlights.setText("Search Flight");
        searchFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightsActionPerformed(evt);
            }
        });
        jMenu2.add(searchFlights);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Status");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jMenu3.add(back);

        exits.setText("Exit");
        exits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitsActionPerformed(evt);
            }
        });
        jMenu3.add(exits);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Search_Flight_Details ob=new Search_Flight_Details();
        ob.setVisible(true);
        
    }//GEN-LAST:event_bookTicketsActionPerformed

    private void cancelticketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelticketsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Cancel_Flight_Ticket ob=new Cancel_Flight_Ticket();
        ob.setVisible(true);
    }//GEN-LAST:event_cancelticketsActionPerformed

    private void showAllTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllTicketsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        booked ob=new booked();
        ob.setVisible(true);
    }//GEN-LAST:event_showAllTicketsActionPerformed

    private void searchFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFlightsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Search_Flight_Details ob=new Search_Flight_Details();
        ob.setVisible(true);
    }//GEN-LAST:event_searchFlightsActionPerformed

    private void addFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Add_Flight_Details ob=new Add_Flight_Details();
        ob.setVisible(true);
    }//GEN-LAST:event_addFlightsActionPerformed

    private void exitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitsActionPerformed
        // TODO add your handling code here:
        JFrame frame=new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","EXIT",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exitsActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
                setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addFlights;
    private javax.swing.JMenuItem back;
    private javax.swing.JMenuItem bookTickets;
    private javax.swing.JMenuItem canceltickets;
    private javax.swing.JMenuItem exits;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem searchFlights;
    private javax.swing.JMenuItem showAllTickets;
    // End of variables declaration//GEN-END:variables
}
